# Generated by Django 4.2 on 2024-04-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('meta_score', models.IntegerField()),
                ('imdb_rating', models.FloatField()),
                ('imdb_votes', models.CharField(max_length=20)),
                ('imdb_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('dvd', models.DateField()),
                ('box_office', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('genres', models.ManyToManyField(to='movie.genre')),
                ('ratings', models.ManyToManyField(to='movie.rating')),
            ],
        ),
    ]
